#!/bin/bash
echo '        Compile Script by JosFer        '

# Let's start
export ARCH=arm
export SUBARCH=arm

echo
echo "Which toolchain would you like to use?"

while read -p "sabermod4.7, sabermod4.8, linaro4.9, linaro4.9-15 ?: " cchoice
do
case "$cchoice" in
	sabermod4.7 )
		toolchain="sabermod4.7"
		export CROSS_COMPILE=/home/josfer/dev-kernels/toolchains/sabermod-arm-eabi-4.7/bin/arm-eabi-
		break
		;;
	sabermod4.8 )
		toolchain="sabermod4.8"
		export CROSS_COMPILE=/home/josfer/dev-kernels/toolchains/sabermod-arm-eabi-4.8/bin/arm-eabi-
		break
		;;
	linaro4.9 )
		toolchain="linaro4.9"
		export CROSS_COMPILE=/home/josfer/dev-kernels/toolchains/linaro-arm-eabi-4.9/bin/arm-eabi-
		break
		;;
    linaro4.9-15 )
		toolchain="linaro4.9-15"
		export CROSS_COMPILE=/home/josfer/dev-kernels/toolchains/arm-cortex_a7-linux-gnueabihf-linaro_4.9/bin/arm-eabi-
		break
		;;
esac
done

# Tuneables
version="v1.0.0"
buildname="cm-12.0-falcon-lollipop-$toolchain-$version"
defconfig="falcon_defconfig"
jobs="5"
kerneltype="zImage"
output="../out/falcon"
ps=2048
base=0x00000000
ramdisk_offset=0x01000000
tags_offset=0x00000100
cmdline="console=ttyHSL0,115200,n8 androidboot.console=ttyHSL0 androidboot.hardware=qcom user_debug=31 msm_rtb.filter=0x37 vmalloc=400M utags.blkdev=/dev/block/platform/msm_sdcc.1/by-name/utags androidboot.write_protect=0 zcache androidboot.selinux=permissive"

echo

while read -p "Do you want to make clean (y/n)? " cchoice
do
case "$cchoice" in
	y|Y )
		make clean && make mrproper
		rm -rf ../out/falcon/files && mkdir -p ../out/falcon/files
		rm -rf ozip/boot.img
		rm -rf arch/arm/boot/"$kerneltype"
		mkdir -p ozip/system/lib/modules
		rm -rf out
		mkdir out
		echo
		echo "Done"
		break
		;;
	n|N )
		break
		;;
	* )
		echo
		echo "Invalid try again!"
		echo
		;;
esac
done

echo

while read -p "Do you want to make defconfig (y/n)? " cchoice
do
case "$cchoice" in
	y|Y )
		make $defconfig
		echo
		echo "Done"
		break
		;;
	n|N )
		break
		;;
	* )
		echo
		echo "Invalid try again!"
		echo
		;;
esac
done

CONFIG_LOCALVERSION="cm-12.0-falcon-lollipop-$toolchain-$version"

echo

DATE_START=$(date +"%s")

while read -p "Do you want to build (y/n)? " cchoice
do
echo
case "$cchoice" in
	y|Y )
		make -j$jobs
		echo
		echo "Done"
		cp arch/arm/boot/"$kerneltype" out
		break
		;;
	n|N )
		break
		;;
	* )
		echo
		echo "Invalid try again!"
		echo
		;;
esac
done


if [ -f out/"$kerneltype" ]; then
	echo "Making dt.img..."
	echo
	./dtbToolCM -2 -o out/dt.img -s 2048 -p scripts/dtc/ arch/arm/boot/
	./dtbToolCM -2 -o ../out/falcon/files/dtb -s 2048 -p scripts/dtc/ arch/arm/boot/
	cp out/dt.img ../out/falcon/files
	cp out/"$kerneltype" ../out/falcon/files
	echo "dt.img created and files copied..."
else
	echo "No build found..."
	exit 0;
fi

echo

if [ -f out/"$kerneltype" ]; then
	echo "Making boot.img..."
	echo
	./mkbootimg --kernel out/"$kerneltype" --ramdisk resources/initramfs.img --cmdline "$cmdline" --base $base --pagesize $ps --ramdisk_offset $ramdisk_offset --tags_offset $tags_offset --dt out/dt.img --output ozip/boot.img
	cp ozip/boot.img ../out/falcon/files
else
	echo "No $kerneltype found..."
	exit 0;
fi

if [ -f arch/arm/boot/"$kerneltype" ]; then
	rm -rf ozip/system
	cd ozip
	zip -r ../$buildname.zip .
	mv ../$buildname.zip ../$output
	cd ..
	rm -rf out ozip/system
	echo "Done..."
	rm -rf ozip/boot.img
else
	echo "Can't finish off zip..."
	exit 0;
fi

DATE_END=$(date +"%s")
DIFF=$(($DATE_END - $DATE_START))
echo "Time: $(($DIFF / 60)) minute(s) and $(($DIFF % 60)) seconds."
